const reviewData = [
  {
    id: 1,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    reviewData:
      "A mesmerizing tale of wealth, love, and the American Dream. Fitzgerald's prose is both elegant and haunting.",
    tags: [
      "Classic",
      "Fiction",
      "Roaring Twenties",
      "Love",
      "American Dream",
      "Tragedy",
      "Gatsby",
      "Rich and Poor",
    ],
  },
  {
    id: 2,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    reviewData:
      "A powerful exploration of racial injustice, moral growth, and compassion in the Deep South. A timeless classic.",
    tags: [
      "Classic",
      "Fiction",
      "Racism",
      "Morality",
      "Courage",
      "Southern Literature",
      "Legal Drama",
      "Childhood",
    ],
  },
  {
    id: 3,
    title: "1984",
    author: "George Orwell",
    reviewData:
      "A dystopian masterpiece that explores the dangers of totalitarianism and the manipulation of truth.",
    tags: [
      "Dystopian",
      "Fiction",
      "Totalitarianism",
      "Surveillance",
      "Political Allegory",
      "Big Brother",
      "Thought Police",
      "Warning",
    ],
  },
  {
    id: 4,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    reviewData:
      "Holden Caulfield's journey of self-discovery is a classic exploration of teenage angst and rebellion.",
    tags: [
      "Classic",
      "Fiction",
      "Coming of Age",
      "Rebellion",
      "Teenage Angst",
      "Alienation",
      "New York City",
      "Symbolism",
    ],
  },
  {
    id: 5,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    reviewData:
      "An enchanting adventure in Middle-earth, filled with hobbits, dwarves, elves, and the quest for treasure.",
    tags: [
      "Fantasy",
      "Adventure",
      "Middle-earth",
      "Hobbits",
      "Dwarves",
      "Dragons",
      "Epic",
      "Quest",
    ],
  },
  {
    id: 6,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    reviewData:
      "A delightful comedy of manners, exploring themes of love, class, and societal expectations.",
    tags: [
      "Classic",
      "Romance",
      "Social Commentary",
      "Regency Era",
      "Elizabeth Bennet",
      "Mr. Darcy",
      "Satire",
      "Matchmaking",
    ],
  },
  {
    id: 7,
    title: "The Hunger Games",
    author: "Suzanne Collins",
    reviewData:
      "A gripping tale of survival and rebellion in a dystopian world where teenagers fight for their lives in the Hunger Games.",
    tags: [
      "Dystopian",
      "Young Adult",
      "Survival",
      "Rebellion",
      "Action",
      "Adventure",
      "Katniss Everdeen",
      "Peeta Mellark",
    ],
  },
  {
    id: 8,
    title: "The Alchemist",
    author: "Paulo Coelho",
    reviewData:
      "A philosophical and mystical journey of self-discovery and the pursuit of one's personal legend.",
    tags: [
      "Philosophy",
      "Fiction",
      "Alchemy",
      "Personal Legend",
      "Spirituality",
      "Quest",
      "Dreams",
      "Destiny",
    ],
  },
  {
    id: 9,
    title: "The Road",
    author: "Cormac McCarthy",
    reviewData:
      "A post-apocalyptic odyssey of a father and son, exploring themes of survival, humanity, and hope.",
    tags: [
      "Dystopian",
      "Fiction",
      "Post-Apocalyptic",
      "Father-Son Relationship",
      "Survival",
      "Desolation",
      "Humanity",
      "Hope",
    ],
  },
  {
    id: 10,
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    reviewData:
      "A gripping mystery involving a journalist and a computer hacker as they delve into a dark family history.",
    tags: [
      "Mystery",
      "Thriller",
      "Crime",
      "Hacker",
      "Journalist",
      "Swedish Literature",
      "Investigation",
      "Family Secrets",
    ],
  },
  {
    id: 11,
    title: "The Martian",
    author: "Andy Weir",
    reviewData:
      "An exhilarating tale of survival and resourcefulness as an astronaut fights to stay alive on Mars.",
    tags: [
      "Science Fiction",
      "Survival",
      "Mars",
      "Astronaut",
      "Space",
      "Engineering",
      "Humor",
      "Resilience",
    ],
  },
];

export default reviewData